### ISSUE TITLE
Prepare a template for newsletter

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/bird-house.github.io#15]
Currently it is a google doc. We could use a versioned template which can produce different outputs (pdf, html). Template could be made with Latex, Markdown, .... and being prepared for several languages (English, French).

Maybe a simpler but less attractive way would be to have it as part of the birdhouse-docs using restructured-text.

**Comment by huard** [comment]
Agreed. 
Jupyter apparently uses Medium for their newsletter. https://newsletter.jupyter.org/
Looked quickly into it, looks simple enough. Let me know if you want me to explore it further.

**Comment by huard** [comment]
There ! https://medium.com/birdhouse-newsletter
Note that we can edit stories collaboratively, like on google docs. 
There are apparently tools to export medium posts to other formats: https://github.com/gunar/medium-converter

**Comment by cehbrecht** [comment]
@huard @nilshempelmann 
It looks more professional. Let's try it.

**Comment by huard** [comment]
We could also publish the factsheets that we wrote there, and broadly, publish material related to the project. I suggest you register on medium and I'll add you as editors.

**Comment by tomLandry** [comment]
Medium is a very good choice. By the way, there is a push at CRIM to publish Medium blog entries regularly on technical subjects. I'll see if I can help there.

Tom
________________________________
De : David Huard <notifications@github.com>
Envoyé : 6 avril 2018 07:54:54
À : bird-house/bird-house.github.io
Cc : Subscribed
Objet : Re: [bird-house/bird-house.github.io] Prepare a template for newsletter (#15)


We could also publish the factsheets that we wrote there, and broadly, publish material related to the project. I suggest you register on medium and I'll add you as editors.

**Comment by huard** [comment]
Excellent. A post on what CRIM did with Testbed 13 would be nice.

**Comment by cehbrecht** [comment]
Tried to figure out how to make comments on Medium:
https://medium.com/@ev/why-medium-notes-are-different-and-how-to-use-them-well-5972c72b18f2

Wanted to have an eye-catcher image at the top of an article like here:
https://engineering.circle.com/productive-with-docker-in-20-minutes-8997297a35bb

You can select also an image as preview:

> Feature an image on your story. In the “Publish” drop-down menu, you can select which of the hi-res images from your story is featured in previews. Or select an image and hit “Shift+F.”

Taken from here:
https://blog.medium.com/tips-and-tricks-for-medium-writers-1d79498101c3

**Comment by huard** [comment]
Good idea. @tomLandry, do you have pictures of the Montréal workshop ? We could put a photo of you guys in a meeting. Or a picture of Montréal.

**Comment by cehbrecht** [comment]
> We could put a photo of you guys in a meeting. Or a picture of Montréal.

I would prefer Montréal (maybe in snow) :)

**Comment by tomLandry** [comment]
@huard: on content, I suggest we go straight to Testbed-14. Like a recap of the OGC Kick-Off meeting (happeing next week) as we seen it, with emphasis on Birdhouse -> PAVICS -> ESA's TEP. Also, we could publish part of the upcoming CRIM technical report on PAVICS there too.

**Comment by huard** [comment]
Sounds good.

**Comment by huard** [comment]
https://getpublii.com/blog/newsletter-opt-in-gdpr-compliance.html

**Comment by nilshempelmann** [comment]
Medium page is set up. 
two newletter posts (english and french) are in place.

**Comment by cehbrecht** [comment]
done
