### ISSUE TITLE
MAGIC spec

### ISSUE THREAD

**Issue by huard** [bird-house/bird-house.github.io#18]
Send MAGIC spec to David and Ben. Including IRIS/Dask support. Provide contact to Bill Little, Met Office.

**Comment by cehbrecht** [comment]
Here are infos I got from Bill (@bjlittle) about Iris and Dask:

> Yes, it’s true that since Iris 2.0 we now utilise the benefit of Dask for deferred loading, out-of-core lazy evaluation and distributed processing.
> 
> I’d recommend going through the Dask documentation https://dask.pydata.org/en/latest/, other than that we did put together a [notebook](http://nbviewer.jupyter.org/github/SciTools/courses/blob/dask_course/course_content/notebooks/dask_intro.ipynb?create=1) as an introduction to dask.
>
> We also added a section to the iris user guide on [real and lazy data](https://scitools.org.uk/iris/docs/latest/userguide/real_and_lazy_data.html).
>
> Is this the kind of information that you’re looking for?

**Comment by cehbrecht** [comment]
@bekozi, @huard:
There is also a SciPy conference in July in Texas where Bill will attend:
https://scipy2018.scipy.org/

**Comment by huard** [comment]
Thanks, I've started looking it Iris and will continue to investigate. There is a lot to like.

**Comment by tomLandry** [comment]
I have thrown the link to my colleagues. Just tell if investigation is required, I can start separate work on HPC technologies and libraries.

**Comment by huard** [comment]
I think the killer feature Iris provides is an abstraction for ensembles ("data cube"). It has capabilities to go through a list of files and cluster them in the smallest number of logical "cubes". I suggest we consider this to improve our search capability. At the moment search returns a list of individual files. I think we should start thinking about a different search interface that returns "cubes" instead of files. 

What I mean is that currently we return a list of items, and then it is the user job to aggregate them. It might be easier to let the platform aggregate, and then let the user filter out the unwanted content. Something to think about.

**Comment by bekozi** [comment]
> I think the killer feature Iris provides is an abstraction for ensembles ("data cube"). It has capabilities to go through a list of files and cluster them in the smallest number of logical "cubes".

That is nice!

**Comment by huard** [comment]
Are there any action item related to this ?

**Comment by bekozi** [comment]
I'm still not sure what this spec is yet. Is it a document or reference implementation? It sounds like it may just be Iris or a part of it. Did I miss a link?

**Comment by huard** [comment]
Don't worry, I'm confused too, and I opened the ticket !
@cehbrecht, was the idea to provide Ben with an example of dask integration or you had something else in mind?

**Comment by cehbrecht** [comment]
Well, I just wanted to make the introduction to Bill who is working on IRIS, and version 2.0 of IRIS is using dask. The rest is up to you :)

The upcoming esmvaltool 2.0 version is also using IRIS:
https://esmvaltool.readthedocs.io/en/version2_development/

**Comment by bekozi** [comment]
> Well, I just wanted to make the introduction to Bill who is working on IRIS, and version 2.0 of IRIS is using dask.

Got it. Hi, @bjlittle! Thanks for the reference materials.

> The rest is up to you :)

That doesn't sounds like magic, sounds like work. :smile:

**Comment by bjlittle** [comment]
Hi Guys, will any of you be at SciPy 2018, Austin, Texas this month? I'll be attending, so if you want to meet-up I'm happy to do so and talk Iris, if that helps :-)

**Comment by tomLandry** [comment]
No, my conference travels will bring me at IGARSS at the end of July, then FOSS4G at the end of August.

I'll do one more call to colleague for SciPy. My organisation, CRIM, would have enough show at the conference for sure.

Tom
________________________________
De : Bill Little <notifications@github.com>
Envoyé : 3 juillet 2018 05:55:36
À : bird-house/bird-house.github.io
Cc : Tom Landry; Comment
Objet : Re: [bird-house/bird-house.github.io] MAGIC spec (#18)


Hi Guys, will any of you be at SciPy 2018, Austin, Texas this month? I'll be attending, so if you want to meet-up I'm happy to do so and talk Iris, if that helps :-)
