### ISSUE TITLE
Documentation on matlab access

### ISSUE THREAD

**Issue by huard** [bird-house/bird-house.github.io#20]
See https://publicwiki.deltares.nl/pages/viewpage.action?pageId=92571618
I think it would be usefult to add a section in the documentation about this so we pop up when people search for matlab wps.

**Comment by tomLandry** [comment]
Overall, the deltares doc is very good.

**Comment by cehbrecht** [comment]
I have added to the tutorials ... at least to have it somewhere:
http://birdhouse.readthedocs.io/en/latest/tutorial/index.html
