### ISSUE TITLE
Support for OpenDAP (or in general streaming services) for WPS (inputs).

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/bird-house.github.io#21]
... currently we just use workarounds (#11).

**Comment by huard** [comment]
# Problem description (please clarify)

NetCDF servers and client libraries support streaming. This is useful to query remotely file metadata or data slices without downloading the entire file. In the pyWPS inplementation, if we configure a `ComplexInput` as having a `application/x-netcdf` mimetype, and then pass a link for a netCDF stream, it will download the file locally (is this correct?). It would be preferable if instead the file was downloaded locally only if the file server does not support streaming.

**Comment by huard** [comment]
OPeNDAP support added in PyWPS.
