### ISSUE TITLE
Use mailchimp for "marketing" newsletters?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/bird-house.github.io#26]
Replace current wps mailing list with mailchimp for newsletters:
https://mailchimp.com/ 

Mailchimp is prepared for GDPR:
https://getpublii.com/blog/newsletter-opt-in-gdpr-compliance.html

See also tickets: #15, #25.

**Comment by nilshempelmann** [comment]
set up and in place. 
Now we have to gain experience with it
