### ISSUE TITLE
Support Python 3.6

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/bird-house.github.io#6]
Run WPS service both with Python 2.7 and 3.x.

**Comment by cehbrecht** [comment]
Currently the Python `supervisor` module is a blocker ... only supports Python 2.x.

**Comment by huard** [comment]
See https://stackoverflow.com/questions/19796883/supervisord-for-python-3 for options.

**Comment by cehbrecht** [comment]
I consider this as done. All birds are now using the new deployment and can decide on their own which Python version they want to use.
