### ISSUE TITLE
Ansible deployment

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/bird-house.github.io#8]
This is a requirement by Copernicus.

**Comment by huard** [comment]
Do you think it would be useful to have a couple of ansible playbooks? My use case would be to install only the dependencies required to build the docs. With the autoprocess directive, this can include a number of dependencies, but typically less than the full server stack.

**Comment by cehbrecht** [comment]
I need to work on Ansible and hopefully have an initial working version ready end of April. The current idea is that the Ansible scripts are not part of the birds. Buildout won't be necessary anymore. A bird will only be a Python package with a conda environment. The conda environment only has the dependencies needed by the bird itself (pywps + dependencies for the processes). Nginx, supervisor will not be part of the bird anymore.  

A bird could be used in two ways (or more):
* git clone the bird, create conda env, start the bird using pywps only (Werkzeug) for demo, tests and development ... or just create the docs.
* use ansible to deploy the bird together with the full stack (Nginx, Supervisor) with customized configs.

The first mode is already possible:
http://emu.readthedocs.io/en/latest/dev_guide.html#running-wps-service-in-test-environment

If you like you can add an additional conda environment file without the overhead (nginx, supervisor, gunicorn).

I don't think you need Ansible for the doc generation.

**Comment by cehbrecht** [comment]
Closing this one. Comments can still be added to:
https://github.com/bird-house/cookiecutter-birdhouse/issues/30
